# -*- coding: utf-8 -*-
"""animal_classifier_optimized.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QoT_1_yTGv7X6-U2Uh6R5aMRVHFkra2y
"""

!pip install opendatasets --quiet
import opendatasets as od
od.download("https://www.kaggle.com/datasets/andrewmvd/animal-faces")

import torch
from torch import nn
from torch.optim import Adam
from torchvision.transforms import transforms
from torch.utils.data import Dataset, DataLoader
from sklearn.preprocessing import LabelEncoder
import matplotlib.pyplot as plt
from PIL import Image
import pandas as pd
import numpy as np
import os

device = "cuda" if torch.cuda.is_available() else "cpu"
print("Device Available: ", device)

image_path = []
labels = []

for i in os.listdir("/content/animal-faces/afhq"):
  for label in os.listdir(f"/content/animal-faces/afhq/{i}"):
    for image in os.listdir(f"/content/animal-faces/afhq/{i}/{label}"):
      image_path.append(f"/content/animal-faces/afhq/{i}/{label}/{image}")
      labels.append(label)

data_df = pd.DataFrame(zip(image_path, labels), columns = ["image_path", "labels"])
print(data_df["labels"].unique())
data_df.head()

# =====================================================
# PERBAIKAN 1: Data Split 70 / 15 / 15
# Sebelumnya: 70 train, 15 val, 15 test (tidak berubah angka,
# tapi sekarang split lebih bersih dari data asli tanpa kebocoran
# antara train/val/test yang sebelumnya berasal dari sumber campur)
# =====================================================
data_df = data_df.sample(frac=1, random_state=42).reset_index(drop=True)  # shuffle dulu

n = len(data_df)
train_end = int(0.70 * n)
val_end   = int(0.85 * n)

train = data_df.iloc[:train_end]
val   = data_df.iloc[train_end:val_end]
test  = data_df.iloc[val_end:]

print(f"Train: {train.shape}, Val: {val.shape}, Test: {test.shape}")

label_encoder = LabelEncoder()
label_encoder.fit(data_df["labels"])

# =====================================================
# PERBAIKAN 2: Data Augmentation untuk training
# Menambahkan random flip, color jitter, dan random rotation
# agar model lebih general dan tidak hafal data training
# =====================================================
train_transform = transforms.Compose([
    transforms.Resize((128, 128)),
    transforms.RandomHorizontalFlip(p=0.5),
    transforms.RandomRotation(degrees=15),
    transforms.ColorJitter(brightness=0.2, contrast=0.2, saturation=0.2, hue=0.1),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406],
                         std=[0.229, 0.224, 0.225]),
])

# Val/Test hanya resize dan normalize (tanpa augmentasi)
eval_transform = transforms.Compose([
    transforms.Resize((128, 128)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406],
                         std=[0.229, 0.224, 0.225]),
])

class CustomImageDataset(Dataset):
  def __init__(self, dataframe, transform=None):
    self.dataframe = dataframe.reset_index(drop=True)
    self.transform = transform
    self.labels = torch.tensor(
        label_encoder.transform(self.dataframe['labels'])
    ).to(device)

  def __len__(self):
    return len(self.dataframe)

  def __getitem__(self, idx):
    img_path = self.dataframe.iloc[idx, 0]
    label = self.labels[idx]
    image = Image.open(img_path).convert('RGB')
    if self.transform:
      image = self.transform(image).to(device)
    return image, label

# =====================================================
# PERBAIKAN 3: Hyperparameter
# Batch size 32 (lebih stabil), epochs 20 (dengan early stopping)
# LR tetap 1e-4 tapi ditambah weight decay 1e-4 (L2 regularization)
# =====================================================
LR         = 1e-4
BATCH_SIZE = 32
EPOCHS     = 20
PATIENCE   = 5   # early stopping

train_dataset = CustomImageDataset(dataframe=train, transform=train_transform)
val_dataset   = CustomImageDataset(dataframe=val,   transform=eval_transform)
test_dataset  = CustomImageDataset(dataframe=test,  transform=eval_transform)

train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True)
val_loader   = DataLoader(val_dataset,   batch_size=BATCH_SIZE, shuffle=False)
test_loader  = DataLoader(test_dataset,  batch_size=BATCH_SIZE, shuffle=False)

print(f"Train batches: {len(train_loader)}, Val batches: {len(val_loader)}, Test batches: {len(test_loader)}")

# =====================================================
# PERBAIKAN 4: Arsitektur Model
# Ditambahkan BatchNorm2d setelah setiap conv layer dan
# Dropout sebelum fully connected layer untuk regularisasi
# =====================================================
class Net(nn.Module):
  def __init__(self):
    super().__init__()

    self.features = nn.Sequential(
        # Block 1
        nn.Conv2d(3, 32, kernel_size=3, padding=1),
        nn.BatchNorm2d(32),
        nn.ReLU(),
        nn.MaxPool2d(2, 2),

        # Block 2
        nn.Conv2d(32, 64, kernel_size=3, padding=1),
        nn.BatchNorm2d(64),
        nn.ReLU(),
        nn.MaxPool2d(2, 2),

        # Block 3
        nn.Conv2d(64, 128, kernel_size=3, padding=1),
        nn.BatchNorm2d(128),
        nn.ReLU(),
        nn.MaxPool2d(2, 2),
    )

    self.classifier = nn.Sequential(
        nn.Flatten(),
        nn.Dropout(p=0.5),           # Dropout 50%
        nn.Linear(128 * 16 * 16, 256),
        nn.ReLU(),
        nn.Dropout(p=0.3),           # Dropout 30%
        nn.Linear(256, len(data_df['labels'].unique())),
    )

  def forward(self, x):
    x = self.features(x)
    x = self.classifier(x)
    return x

model = Net().to(device)
print(model)

criterion = nn.CrossEntropyLoss()

# Weight decay = L2 regularization
optimizer = Adam(model.parameters(), lr=LR, weight_decay=1e-4)

# =====================================================
# PERBAIKAN 5: Learning Rate Scheduler
# Jika val loss tidak turun selama 3 epoch, LR dikurangi 50%
# =====================================================
scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(
    optimizer, mode='min', factor=0.5, patience=3
)

total_loss_train_plot = []
total_loss_validation_plot = []
total_acc_train_plot = []
total_acc_validation_plot = []

# =====================================================
# PERBAIKAN 6: Early Stopping
# Training berhenti jika val loss tidak membaik selama PATIENCE epoch
# =====================================================
best_val_loss = float('inf')
patience_counter = 0

for epoch in range(EPOCHS):
  # --- Training ---
  model.train()
  total_acc_train = 0
  total_loss_train = 0

  for inputs, labels in train_loader:
    optimizer.zero_grad()
    outputs = model(inputs)
    train_loss = criterion(outputs, labels)
    total_loss_train += train_loss.item()
    train_loss.backward()
    train_acc = (torch.argmax(outputs, axis=1) == labels).sum().item()
    total_acc_train += train_acc
    optimizer.step()

  # --- Validation ---
  model.eval()
  total_loss_val = 0
  total_acc_val = 0

  with torch.no_grad():
    for inputs, labels in val_loader:
      outputs = model(inputs)
      val_loss = criterion(outputs, labels)
      total_loss_val += val_loss.item()
      val_acc = (torch.argmax(outputs, axis=1) == labels).sum().item()
      total_acc_val += val_acc

  avg_train_loss = total_loss_train / len(train_loader)
  avg_val_loss   = total_loss_val   / len(val_loader)
  train_acc_pct  = round((total_acc_train / len(train_dataset)) * 100, 4)
  val_acc_pct    = round((total_acc_val   / len(val_dataset))   * 100, 4)

  total_loss_train_plot.append(avg_train_loss)
  total_loss_validation_plot.append(avg_val_loss)
  total_acc_train_plot.append(train_acc_pct)
  total_acc_validation_plot.append(val_acc_pct)

  print(f'Epoch {epoch+1}/{EPOCHS} | '
        f'Train Loss: {avg_train_loss:.4f} Acc: {train_acc_pct}% | '
        f'Val Loss: {avg_val_loss:.4f} Acc: {val_acc_pct}%')

  # Update scheduler
  scheduler.step(avg_val_loss)

  # Early stopping check
  if avg_val_loss < best_val_loss:
    best_val_loss = avg_val_loss
    patience_counter = 0
    torch.save(model.state_dict(), 'best_model.pth')  # simpan model terbaik
  else:
    patience_counter += 1
    if patience_counter >= PATIENCE:
      print(f'Early stopping di epoch {epoch+1}')
      break

# Load model terbaik
model.load_state_dict(torch.load('best_model.pth'))
print('Model terbaik berhasil dimuat.')

fig, axes = plt.subplots(1, 2, figsize=(14, 5))

axes[0].plot(total_loss_train_plot, label='Training Loss')
axes[0].plot(total_loss_validation_plot, label='Validation Loss')
axes[0].set_title('Training and Validation Loss over Epochs')
axes[0].set_xlabel('Epochs')
axes[0].set_ylabel('Loss')
axes[0].legend()

axes[1].plot(total_acc_train_plot, label='Training Accuracy')
axes[1].plot(total_acc_validation_plot, label='Validation Accuracy')
axes[1].set_title('Training and Validation Accuracy over Epochs')
axes[1].set_xlabel('Epochs')
axes[1].set_ylabel('Accuracy (%)')
axes[1].legend()

plt.tight_layout()
plt.savefig('training_curves.png', dpi=150)
plt.show()

# Evaluasi pada test set
model.eval()
total_test_correct = 0

with torch.no_grad():
  for inputs, labels in test_loader:
    outputs = model(inputs)
    preds = torch.argmax(outputs, axis=1)
    total_test_correct += (preds == labels).sum().item()

test_acc = (total_test_correct / len(test_dataset)) * 100
print(f'Test Accuracy: {test_acc:.2f}%')

import requests
from io import BytesIO

def predict_from_url(url):
    response = requests.get(url)
    image = Image.open(BytesIO(response.content)).convert('RGB')
    image = eval_transform(image).to(device)
    with torch.no_grad():
        output = model(image.unsqueeze(0))
    output = torch.argmax(output, axis=1).item()
    return label_encoder.inverse_transform([output])

# Contoh pakai URL gambar kucing
predict_from_url("https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Cat03.jpg/320px-Cat03.jpg")